### ISSUE TITLE
Bayern 

### ISSUE THREAD

**Issue by woleonard** [okfde/ifg-index#19]
Wenn ich im Dropdown-Menü Bayern wähle, werde ich aktuell auf die Startseite verlinkt.

![bildschirmfoto 2017-03-01 um 12 57 44](https://cloud.githubusercontent.com/assets/22006947/23459067/23b5dd6a-fe7f-11e6-8734-a6f21664e790.png)

**Comment by woleonard** [comment]
Ebenfalls auch wenn ich auf der Landkarte auf "Bayern" klicke, werde ich auf die Startseite geleitet.

**Comment by arnese** [comment]
Das liegt daran, dass der Link noch auf "Bayern" geht, nicht auf "bayern"
