### ISSUE TITLE
Gesetze bei uns darstellen

### ISSUE THREAD

**Issue by arnese** [okfde/ifg-index#25]
Es wäre schön, alle IFG-Gesetzestexte bei uns im selben Format vorliegen zu haben. Dann könnte man darauf verlinken, könnte Gesetzesänderungen darstellen und allerlei Spielereien veranstalten.
Derzeit müsste nach außen verlinkt werden, das ist nicht so schön.
(Nachteil: Muss man aktuell halten. Ist aber nicht sonderlich aufwändig, nur nicht unbedingt nachhaltig.)

**Comment by stadine** [comment]
Also eine Detailseite mit Bundeslandauswahl und dem Gesetzestext und Sprungmarken zu den Indikatoren?

**Comment by arnese** [comment]
Genau. Aus der Bundeslandseite sollte man auf Absätze des Gesetzestextes linken können (andersrum wohl nicht so wichtig)

**Comment by krmax44** [comment]
Wo sollten die Gesetzestexte am besten liegen? Gleich auf FragDenStaat oder als Unterseite hier?

**Comment by arnese** [comment]
Am besten direkt bei FDS, oder? Dann haben wirs da schon mal.

**Comment by krmax44** [comment]
kommt in okfde/froide#430
