### ISSUE TITLE
Indikatorenvergleich

### ISSUE THREAD

**Issue by stadine** [okfde/ifg-index#26]
![indikatoren-detailseite](https://cloud.githubusercontent.com/assets/7421063/25901150/20d44584-3596-11e7-8ddc-336ac915b3b3.jpg)
![indikatoren-detailseite-kategorien-ausgeklappt](https://cloud.githubusercontent.com/assets/7421063/25901154/240c4c10-3596-11e7-9297-0cd9015a8cfa.jpg)
![indikatoren-detailseite-indikator-ausgeklappt-1](https://cloud.githubusercontent.com/assets/7421063/25901161/25cd01b6-3596-11e7-9d07-7ddd63063446.jpg)
![indikatoren-detailseite-indikatoren-ausgeklappt-2](https://cloud.githubusercontent.com/assets/7421063/25901165/2792ff46-3596-11e7-86ee-9c3b152d6460.jpg)

**Comment by stadine** [comment]
Ich habe mich gegen die Integration des Gesetzestext entschieden, da dieser recht redundant zu der Indikatorenbeschreibung ist.

**Comment by arnese** [comment]
Das sieht sehr gut aus! Welche Möglichkeit gäbe es denn dann, die Unterschiede in der Punktebewertung zu erklären? Ein Link?

**Comment by stadine** [comment]
@arnese untendrunter steht text?

**Comment by arnese** [comment]
ok!
