### ISSUE TITLE
Internationalen Vergleich

### ISSUE THREAD

**Issue by arnese** [okfde/ifg-index#33]
Vergleich von Deutschland mit anderen Ländern ist sinnvoll. Zumindest die Darstellung, dass fast alle anderen europäischen Länder ein IFG haben.

**Comment by knutator2** [comment]
gibts irgendwas offizielles woran man das messen kann. Open Data Index oder so?

**Comment by arnese** [comment]
![europa](https://user-images.githubusercontent.com/9381889/35982863-1a5996f4-0cf1-11e8-918f-4c00c6671544.jpg)
das hier gibt's.
