### ISSUE TITLE
Links zu FDS-Blog auf Länderseiten

### ISSUE THREAD

**Issue by arnese** [okfde/ifg-index#35]
Neue Sektion mit Neuigkeiten aus den Bundesländern

**Comment by arnese** [comment]
Nicht sinnvoll. Stattdessen Links auf FDS-Blog jeweils mit Tag zu Bundesland.

**Comment by krmax44** [comment]
So, oder zu unsichtbar? Link nach Main Content, Text ist `Aktuelles zu Baden-Württemberg im FragDenStaat-Blog`

![Screenshot from 2021-03-12 10-44-39](https://user-images.githubusercontent.com/12673799/110922451-fdc98780-831f-11eb-8ffe-f76fc8fbb578.png)

**Comment by arnese** [comment]
Gut! Vielleicht noch etwas hervorheben, z.B. mit →  oder in fett oder so?
