### ISSUE TITLE
Add Links to FragDenStaat.de

### ISSUE THREAD

**Issue by jfilter** [okfde/ifg-index#37]
For SEO. 

1) Link in the Footer -> https://fragdenstaat.de
2) "Um mehr über Informationsfreiheit und Informationsfreiheitgesetze zu erfahren bietet FragDenStaat einen Einstieg" -> https://fragdenstaat.de/info/informationsfreiheit/einfuehrung/

**Comment by arnese** [comment]
https://github.com/okfde/transparenzranking.de/commit/b1f2bc50d1f30066f658a21b42343166915cb553
