### ISSUE TITLE
Filter in Mobil-Version als Dropdown

### ISSUE THREAD

**Issue by stadine** [okfde/ifg-index#6]
Es wäre super, wenn die Filter für das Balkendiagramm in der Mobilversion zu einem Dropdown. Sonst wird es zu lang. 

Ich füge es in Sketch hinzu!

**Comment by arnese** [comment]
@stadine ist das jetzt ok?

**Comment by apriljunge** [comment]
@stadine @arnese Wie ist der Status hier?
Passt das erstmal so?
