### ISSUE TITLE
Nutzung eines Ihrer Diagramme für ein Buch

### ISSUE THREAD

**Issue by JensWilhelm** [okfde/ifg-index#71]
ich möchte gerne eines Ihrer Diagramme für ein Buch benutzen, das im Herbst im Wiley-Verlag erscheint und benötige dafür Ihr Einverständnis.
[https://transparenzranking.de/](url)

@stefanw

**Comment by krmax44** [comment]
Die Inhalte sind unter [Creative Commons Namensnennung 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) lizenziert und können mit entsprechender Nennung frei verwendet werden.
