### ISSUE TITLE
Farbigkeit der Karte

### ISSUE THREAD

**Issue by stadine** [okfde/ifg-index#9]
Wir könnten die Länder, in denen es kein IFG gibt rot einfärben und eine dramatische Melodie abspielen, da es keine Detailseiten gibt. Dööööö Döööööööööö

@arnese Oder willst du eine Detailseite haben?

**Comment by arnese** [comment]
Ja, eine Detailseite ist schon sinnvoll. Sonst begreifen Leute aus Bayern nicht direkt, warum sie nicht auf eine bayerische Seite kommen.

**Comment by knutator2** [comment]
ok, dann füg ich einfach null Daten in das google sheet ein. Wollen wir die Karten ohne IFG trotzdem rot einfärben?

**Comment by arnese** [comment]
rot bei Nicht-IFG-Bundesländern mindestens
